### ISSUE TITLE
Issue Related to draw_line_from_file 

### ISSUE THREAD

**Issue by SagarP-GPU** [Tim-Saijun/Web-page-Screenshot-Segmentation#9]
draw_line_from_file function is not available in  spliter file

**Comment by Ryaang** [comment]
Sorry, this function is in `drawer.py`. So you can use this function by:
```python
from Web_page_Screenshot_Segmentation.drawer import draw_line_from_file
```

**Comment by SagarP-GPU** [comment]
I tried with drawer too but is like 

Output -The modified image is saved at c:\Audit_Software\result\C:\Audit_Software\Screenshots\zohoresult.jpg

but even it creates result folder it is not able to save image

**Comment by SagarP-GPU** [comment]
Can be possible to make like Segment it with both image and HTML for Structure I think it would be better
